spring.application.name=backendpractice
spring.datasource.url=jdbc:postgresql://localhost:5432/backendpractice
spring.datasource.username=kawabuchidaisuke
spring.datasource.password=


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true